#!/usr/bin/env bash
#==============================================================================
# Prepare UFSCAR's ArchLinux generic lab image
#==============================================================================
# Created and mantained by PedroHLC <root@pedrohlc.com>
# Last Update: 2020-03-07 15:10
#------------------------------------------------------------------------------


#==============================================================================
# Pre-setup preparations
#==============================================================================
# Set script options
#------------------------------------------------------------------------------
set -o errexit

#------------------------------------------------------------------------------
# Verify constraints
#------------------------------------------------------------------------------
[[ "$(whoami)" == 'root' ]] && echo 'Not expected to be built using root' && exit -1

#------------------------------------------------------------------------------
# Define constants & settings
#------------------------------------------------------------------------------
readonly _TARGET_ARCH='x86_64'
readonly _TARGET_FLAVOR='generic'
readonly _ARTIFACT_STAMP="$(date '+%y.%m')"
readonly _ARTIFACT_BASENAME="ufscar-${_TARGET_FLAVOR}-${_ARTIFACT_STAMP}-$_TARGET_ARCH"
readonly _ARTIFACT_FNAME="${_ARTIFACT_BASENAME}.qcow2"
readonly _ARTIFACT_DEST='/srv/http/chaotic-aur/rootfs/.ufscar/'
readonly _HTTP_DEST='http://lonewolf.pedrohlc.com/chaotic-aur/rootfs/.ufscar/'
readonly _BT_TRACKER='udp://lonewolf.pedrohlc.com:23069'
readonly _BT_LOCAL_TRACKER='udp://192.168.0.1:6969'
readonly _WORK_DIR='/tmp/chaotic-rootfs'
readonly _WORK_FNAME="${_ARTIFACT_BASENAME}.img"

#------------------------------------------------------------------------------
# Prepare build directory
#------------------------------------------------------------------------------
mkdir -p "$_WORK_DIR"
cd "$_WORK_DIR"

#==============================================================================
# Create and mount a virtual raw disk
#==============================================================================
truncate -s 100G "$_WORK_FNAME"
sudo losetup /dev/loop9 "$_WORK_FNAME"
sudo parted /dev/loop9 mktable msdos
sudo parted /dev/loop9 mkpart primary ext4 1M '100%'
sudo partprobe /dev/loop9
sudo mkfs.ext4 -q /dev/loop9p1
sudo mkdir "$_ARTIFACT_BASENAME"
sudo mount -t ext4 /dev/loop9p1 "$_ARTIFACT_BASENAME"
pushd "$_ARTIFACT_BASENAME"

#==============================================================================
# Prepare filesystem and initial settings before chrooting
#==============================================================================
# Install base package
#------------------------------------------------------------------------------
sudo pacstrap -GM . base mkinitcpio

#------------------------------------------------------------------------------
# Set locale
#------------------------------------------------------------------------------
pushd ./etc
sudo rm localtime || echo 'There was no localtime'
sudo ln -s ../usr/share/zoneinfo/America/Sao_Paulo ./localtime
popd

cat <<EOF | sudo cp /dev/stdin ./etc/locale.gen
en_US.UTF-8 UTF-8
pt_BR.UTF-8 UTF-8
EOF

echo 'LANG=pt_BR.UTF-8' | sudo cp /dev/stdin ./etc/locale.conf
echo 'KEYMAP=br-abnt2' | sudo cp /dev/stdin ./etc/vconsole.conf
sudo chmod 644 ./etc/locale.conf

#------------------------------------------------------------------------------
# Set hostname and update it in hosts
#------------------------------------------------------------------------------
echo 'ufscar-pc' | sudo cp /dev/stdin ./etc/hostname

cat <<EOF | sudo tee -a ./etc/hosts > /dev/null
127.0.0.1	localhost
::1		localhost
127.0.1.1	ufscar-pc.localdomain	ufscar
EOF

#------------------------------------------------------------------------------
# Set only brazilian servers in mirrorlist
#------------------------------------------------------------------------------
cat <<EOF | sudo cp /dev/stdin ./etc/pacman.d/mirrorlist
Server = http://mirror.ufscar.br/archlinux/\$repo/os/\$arch
Server = http://archlinux.c3sl.ufpr.br/\$repo/os/\$arch
Server = http://www.caco.ic.unicamp.br/archlinux/\$repo/os/\$arch
Server = https://www.caco.ic.unicamp.br/archlinux/\$repo/os/\$arch
Server = http://linorg.usp.br/archlinux/\$repo/os/\$arch
Server = http://pet.inf.ufsc.br/mirrors/archlinux/\$repo/os/\$arch
Server = http://archlinux.pop-es.rnp.br/\$repo/os/\$arch
Server = http://mirror.ufam.edu.br/archlinux/\$repo/os/\$arch
Server = http://br.mirror.archlinux-br.org/\$repo/os/\$arch
EOF

#------------------------------------------------------------------------------
# Add [chaotic-aur] to pacman.conf
#------------------------------------------------------------------------------
cat <<EOF | sudo tee -a ./etc/pacman.conf > /dev/null
[multilib]
Include = /etc/pacman.d/mirrorlist

[chaotic-aur]
Server = https://lonewolf.pedrohlc.com/\$repo/\$arch
Server = http://chaotic.bangl.de/\$repo/\$arch

[sublime-text]
Server = https://download.sublimetext.com/arch/stable/\$arch
EOF

#------------------------------------------------------------------------------
# Add Virtio SCSI modules to init
#------------------------------------------------------------------------------
sudo sed -i'' 's/^MODULES=(/MODULES=(virtio virtio_scsi virtio_blk virtio_pci virtio_net /' ./etc/mkinitcpio.conf

#------------------------------------------------------------------------------
# Add a swapfile
#------------------------------------------------------------------------------
sudo truncate -s 0 ./swapfile
sudo fallocate -l 512M ./swapfile
sudo chmod 600 ./swapfile
sudo mkswap ./swapfile

#------------------------------------------------------------------------------
# Generate fstab
#------------------------------------------------------------------------------
genfstab -U /mnt | awk '!/swap/' | echo '/swapfile none swap defaults 0 0' | sudo tee -a ./etc/fstab > /dev/null

#==============================================================================
# Enter chroot and complete installation
#==============================================================================
sudo arch-chroot . /usr/bin/bash <<EOF
#!/usr/bin/bash
set -o errexit

# Set BIOS time mode and generate locale files
hwclock --systohc
locale-gen

# Initiate keyring and add [chaotic-aur] keys
pacman-key --init
pacman-key --populate archlinux
pacman-key --keyserver hkps://hkps.pool.sks-keyservers.net -r ADAE6AD28A8F901A
pacman-key --lsign-key 1EDDE2CDFC025D17F6DA9EC0ADAE6AD28A8F901A
pacman-key --keyserver keys.mozilla.org -r 3056513887B78AEB
pacman-key --lsign-key 3056513887B78AEB 

# Install desired packages
pacman -Syu --noconfirm
pacman -S linux-zen linux-zen-headers --noconfirm
pacman -S --noconfirm --needed \
	base-devel multilib-devel git man \
	sudo yay networkmanager pulseaudio-alsa \
	\
	syslinux efibootmgr \
	ntfs-3g dosfstools mtools exfat-utils un{rar,zip} p7zip \
	gvfs-mtp android-udev-git wget curl \
	\
	nano neovim-drop-in openssh \
	\
	plasma sddm kdebase packagekit-qt5 \
	\
	{,lib32-}mesa {,lib32-}libva-{mesa,intel}-driver {,lib32-}vulkan-icd-loader \
	intel-ucode xf86-video-intel \
	xorg-server {,lib32-}vulkan-intel intel-media-driver \
	\
	firefox google-chrome mpv wine-staging xarchiver \
	wps-office wps-office-mui-pt-br ttf-wps-fonts wps-office-extension-portuguese-brazilian-dictionary \
	quartus-130 libpng12 scilab-bin \
	firefox-ublock-origin firefox-extension-plasma-integration \
	\
	gnu-free-fonts \
	ttf-{dejavu,droid,fira-{code,mono,sans}} \
	ttf-{liberation,ms-fonts,ubuntu-font-family,wps-fonts} \
	\
	rstudio-desktop bluespec iverilog verilator gtkwave sublime-text thonny
pacman -Rsn --noconfirm konqueror

# Create main user
useradd -m -g wheel -G users -s /bin/bash archer
passwd -d root
passwd -d archer
groupadd plugdev
usermod -aG plugdev archer

# Update modules in initramfs
mkinitcpio -Pv
EOF

#------------------------------------------------------------------------------
# Add matlab which package is local
#------------------------------------------------------------------------------
sudo pacman -r . -U ~/'.ufscar/matlab-ufscar-9.7.0.0-0-x86_64.pkg.tar.xz' --noconfirm

#==============================================================================
# With files now in place, change more settings
#==============================================================================
# Enable services
#------------------------------------------------------------------------------
sudo systemctl --root=. enable NetworkManager
sudo systemctl --root=. enable sddm

#------------------------------------------------------------------------------
# Add all real users to sudoers
#------------------------------------------------------------------------------
echo '%wheel ALL=(ALL) ALL' | sudo tee -a ./etc/sudoers > /dev/null

#------------------------------------------------------------------------------
# Add UFSCAR's license server
#------------------------------------------------------------------------------
echo 'export LM_LICENSE_FILE=1800@licencas.ufscar.br' | sudo tee ./etc/profile.d/ufscar.sh > /dev/null

#------------------------------------------------------------------------------
# KDE autologin
#------------------------------------------------------------------------------
sudo mkdir ./etc/sddm.conf.d
sudo chmod 755 ./etc/sddm.conf.d
cat <<EOF | sudo tee -a ./etc/sddm.conf.d/00-ufscar.conf > /dev/null
[Autologin]
User=archer
Session=plasma

[Theme]
Current=breeze
EOF
sudo chmod 600 ./etc/sddm.conf.d/00-ufscar.conf

#------------------------------------------------------------------------------
# KDE keyboard
#------------------------------------------------------------------------------
cat <<EOF | sudo tee -a ./etc/xdg/kxkbrc > /dev/null
[Layout]
LayoutList=br
LayoutLoopCount=-1
Model=pc101
Use=true
EOF
sudo chmod 644 ./etc/xdg/kxkbrc

#------------------------------------------------------------------------------
# KDE locale
#------------------------------------------------------------------------------
cat <<EOF | sudo tee -a ./etc/xdg/plasma-localerc > /dev/null
[Formats]
LANG=pt_BR.UTF-8

[Translations]
LANGUAGE=pt_BR
EOF
sudo chmod 644 ./etc/xdg/plasma-localerc

#------------------------------------------------------------------------------
# KDE theme
#------------------------------------------------------------------------------
cat <<EOF | sudo tee -a ./etc/xdg/plasmarc > /dev/null
[Theme]
name=breeze-dark
EOF
sudo chmod 644 ./etc/xdg/plasmarc

#------------------------------------------------------------------------------
# Remove Suspend / Hibernate
#------------------------------------------------------------------------------
cat <<EOF | sudo tee ./etc/polkit-1/rules.d/55-inhibit-causevm.rules > /dev/null
polkit.addRule(function(action, subject) {
    if (action.id == "org.freedesktop.login1.suspend" ||
        action.id == "org.freedesktop.login1.suspend-multiple-sessions" ||
    	action.id == "org.freedesktop.login1.hibernate" ||
        action.id == "org.freedesktop.login1.hibernate-multiple-sessions")
    {
        return polkit.Result.NO;
    }
});

EOF

#------------------------------------------------------------------------------
# I don't like "Área de Trabalho", so set home directories to be in english
#------------------------------------------------------------------------------
sudo mkdir -p ./home/archer/{.config/plasma-workspace/shutdown,Desktop,Downloads,Documents,Music,Pictures,Videos}
cat <<EOF | sudo tee ./home/archer/.config/user-dirs.dirs > /dev/null
XDG_DESKTOP_DIR="\$HOME/Desktop"
XDG_DOWNLOAD_DIR="\$HOME/Downloads"
XDG_TEMPLATES_DIR="\$HOME/Templates"
XDG_PUBLICSHARE_DIR="\$HOME/Public"
XDG_DOCUMENTS_DIR="\$HOME/Documents"
XDG_MUSIC_DIR="\$HOME/Music"
XDG_PICTURES_DIR="\$HOME/Pictures"
XDG_VIDEOS_DIR="\$HOME/Videos"
EOF
echo 'en_US' | sudo tee ./home/archer/.config/user-dirs.locale > /dev/null

#------------------------------------------------------------------------------
# Poweroff on Logout & Halt without Confirmation
#------------------------------------------------------------------------------
cat <<EOF | sudo tee -a ./etc/xdg/ksmserverrc > /dev/null
[General]
confirmLogout=false
shutdownType=2
loginMode=default
EOF
sudo chmod 644 ./etc/xdg/ksmserverrc

#------------------------------------------------------------------------------
# Fix things written as root
#------------------------------------------------------------------------------
sudo arch-chroot . chown -R archer:users /home/archer

#==============================================================================
# Finish install
#==============================================================================
# Clean pacman cache
#------------------------------------------------------------------------------
yes | sudo pacman -r . -Scc

#------------------------------------------------------------------------------
# Install Syslinux
#------------------------------------------------------------------------------
sudo syslinux-install_update -i -a -m -c .
sudo sed -i'' 's/-linux/-linux-zen/g;s/TIMEOUT.*$//g;s/UI.*$//g;s/MENU.*$//g;s/sda3/sda1/g' ./boot/syslinux/syslinux.cfg


#------------------------------------------------------------------------------
# Fix WPS Office PT-BR Spell checking
#------------------------------------------------------------------------------
sudo sed -i'' '2iexport LANG=en_US.UTF-8' ./usr/bin/wps ./usr/bin/wpp

#------------------------------------------------------------------------------
# Recovery sparse space
#------------------------------------------------------------------------------
echo '[@] Converting image, this can take a while...'
sudo fstrim -v .

#------------------------------------------------------------------------------
# Umount rootfs
#------------------------------------------------------------------------------
popd
sudo umount -Rv "$_ARTIFACT_BASENAME"
sudo sync

#------------------------------------------------------------------------------
# Umount disk image
#------------------------------------------------------------------------------
sudo losetup -d /dev/loop9
sudo rmdir "$_ARTIFACT_BASENAME"

#------------------------------------------------------------------------------
# Run the system once, so it starts faster later
#------------------------------------------------------------------------------
#echo '[@] Running system once, this will take 6 minutes'
#(sleep 300; echo; echo system_powerdown) | qemu-system-x86_64 -m 3G -enable-kvm "$_WORK_FNAME" -vnc :13 -monitor stdio -serial none > /dev/null

#------------------------------------------------------------------------------
# Convert image to QCOW2, deletes original
#------------------------------------------------------------------------------
echo '[@] Converting image, this can take a while...'
qemu-img convert -W -m 16 -f raw -O qcow2 -c "$_WORK_FNAME" "${_ARTIFACT_FNAME}"
sudo rm "$_WORK_FNAME"

#------------------------------------------------------------------------------
# Sign file, creates a torrent file, and deploy them all to the final directory
#------------------------------------------------------------------------------
echo '[@] Signing'
gpg --detach-sign --use-agent --no-armor "./${_ARTIFACT_FNAME}"

echo '[@] Torrenting'
mktorrent -w "${_HTTP_DEST}/${_ARTIFACT_FNAME}" -a "${_BT_LOCAL_TRACKER}" -a "${_BT_TRACKER}" "./${_ARTIFACT_FNAME}"

echo '[@] Deploying'
cp -v ./"${_ARTIFACT_FNAME}"{,.sig,.torrent} "$_ARTIFACT_DEST"

echo '[@] Finishing creating ' "${_ARTIFACT_FNAME}"
