#!/bin/bash
setup_wine() {
	git checkout customization.cfg PKGBUILD

	sed -i'' "
	s/_COMPILEWITH=\"[^\"]*\"/_COMPILEWITH=\"zapcc\"/g
	s/_OPTIMIZED=\"[^\"]*\"/_OPTIMIZED=\"false\"/g
	s/_NUKR=\"[^\"]*\"/_NUKR=\"false\"/g
	s/_NOINITIALPROMPT=\"[^\"]*\"/_NOINITIALPROMPT=\"true\"/g
	s/_use_staging=\"[^\"]*\"/_use_staging=\"$1\"/g
	s/_use_pba=\"[^\"]*\"/_use_pba=\"$2\"/g
	s/_use_gallium_nine=\"[^\"]*\"/_use_gallium_nine=\"$3\"/g
	" customization.cfg

	local _SRCINFO=$(makepkg -o --noprepare --printsrcinfo)
	export _PKGNAME=$(echo "$_SRCINFO" | grep -Po '(?<=pkgname = )(.*)$')
	export _PKGREL=$(echo "$_SRCINFO" | grep -Po '(?<=pkgrel = )(.*)$')
	#export _PKGVER=$(echo "$_SRCINFO" | grep -Po '(?<=pkgver = )(.*)$')

	echo "[!] Consulting version..."
	export _PKGVER=$(~/chaotic-pkgver | tail -n 1)
}

# we need the base chroot
if [ ! -d /tmp/chaotic-chroot/wine ]; then ~/chaotic-makepkg --version &> /dev/null; fi
arch-nspawn /tmp/chaotic-chroot/wine pacman -Syu zapcc --noconfirm
almostisolated_makepkg() {
	mkdir -p ./iso-me
        makechrootpkg \
                -D "$HOME/.gnupg:/build/.gnupg" \
                -d "$HOME/.ccache:/build/.ccache" \
                -d "${PKGDEST:-/srv/http/chaotic-aur/x86_64}:/pkgdest" \
		-d "${PWD}/iso-me:/build/$_PKGNAME" \
		-d "${PWD}/iso-me:/build/${_PKGNAME/%-git/-opt-git}" \
		-l wine \
                -r /tmp/chaotic-chroot \
                -- \
		--key 3056513887B78AEB \
		--noconfirm --log \
                PKGDEST="/pkgdest" \
                $@
}

cd /tmp
rm -rf TkG
git clone https://github.com/Tk-Glitch/PKGBUILDS.git TkG
cd TkG/wine-tkg-git

for VARIATION in 'false false false' 'false false true' 'false true false' 'true true false' 'true false true' 'true false false'
do
        setup_wine $VARIATION
	
       	_LASTVER_DIR="${HOME}/last-wine/${_PKGREL}"
        _LASTVER_FILE="${_LASTVER_DIR}/${_PKGNAME}"
        mkdir -p "$_LASTVER_DIR"
	
        echo "[!] Package: ${_PKGNAME}-${_PKGVER}-${_PKGREL}"
        if [[ ! -f "$_LASTVER_FILE" || "$(cat $_LASTVER_FILE)" != "$_PKGVER" ]]
        then
        	echo "[!] Building"
		
	        almostisolated_makepkg -sfc --sign --log || continue
		
	        sed -i'' 's/_INSTALL_TO_OPT="false"/_INSTALL_TO_OPT="true"/g' customization.cfg
		
		cd iso-me/src
	        ln -s "${_PKGNAME}-32-build" "${_PKGNAME/%-git/-opt-git}-32-build"
	        ln -s "${_PKGNAME}-64-build" "${_PKGNAME/%-git/-opt-git}-64-build"
		cd ../..
		
	        almostisolated_makepkg -Rf --sign --log
		
		echo "$_PKGVER" > "$_LASTVER_FILE"

		rm -rf ./iso-me/*
	fi
done

cd /tmp
sudo rm -rf TkG
