#!/usr/bin/env bash
~/chaotic-base-update

cd /tmp

BUILDDIR="hourly.$(date '+%Y%m%d%H%M%S')"
mkdir -p "$BUILDDIR" || exit
cd "$BUILDDIR" || exit

repoctl down -u
cat ~/ignore-hourly.txt | xargs rm -rf
repoctl list |\
       	grep '\-\(git\|svn\|bzr\|nightly\)$' |\
       	sort | comm -13 ~/ignore-hourly.txt - |\
	xargs repoctl down
ls | xargs echo '[build-hourly] Building: '
~/chaotic-batchbuild

LOGDIR=/srv/http/chaotic-aur/makepkglogs
mkdir -p "$LOGDIR"
mv ./*.log "$LOGDIR/"

cd ..
rm -rf "$BUILDDIR"

~/chaotic-add
~/chaotic-status > /srv/http/chaotic-aur/analytics.txt

cd "$LOGDIR"
TOREM=$(grep -l -P 'ERROR: (A|The) package( group)? has already been built' *.log)
[[ ! -z "$TOREM" ]] && echo "$TOREM" | xargs rm
TOREM=$(grep -l 'Created signature file' *.log)
[[ ! -z "$TOREM" ]] && echo "$TOREM" | xargs rm
