#!/usr/bin/env bash
LDIR=/srv/http/chaotic-aur/makepkglogs/_daily/schoina
cd /tmp

DESTDIR="schoina"

git clone https://github.com/SolarAquarion/PKGBUILD-CHAOTIC.git "$DESTDIR"
cd "./$DESTDIR" || exit
~/chaotic-batchbuild

mkdir -p "$LDIR"
mv *.log "$LDIR/"

cd /tmp && rm -rf --one-file-system "$DESTDIR"
cd "$LDIR" && ~/chaotic-clean-logs
