#!/bin/bash
echo '[!] Building'
cd /tmp
yaourt -G llvm-svn
cd llvm-svn
export TARGET_EXTRAPKGS='multilib-devel zapcc'
~/chaotic-makepkg --sign -sfc

echo '[!] Nuking'
cd /tmp
sudo rm -rf /tmp/llvm-svn

