#!/usr/bin/env bash
LDIR=/srv/http/chaotic-aur/makepkglogs/_daily/cubocore_
cd /tmp

git clone https://gitlab.com/cubocore/wiki.git
cd ./wiki/PKGBUILD-git || exit
~/chaotic-batchbuild

mkdir -p "$LDIR"
mv *.log "$LDIR/"

cd /tmp && rm -rf --one-file-system ./wiki
cd "$LDIR" && ~/chaotic-clean-logs
