#!/usr/bin/env bash
LDIR=/srv/http/chaotic-aur/makepkglogs/_daily/librewish
cd /tmp

git clone https://github.com/librewish/wishbuilds.git
cd ./wishbuilds/manjarowish || exit
~/chaotic-batchbuild

mkdir -p "$LDIR"
mv *.log "$LDIR/"

cd /tmp && rm -rf ./wishbuilds
cd "$LDIR" && ~/chaotic-clean-logs
