#!/usr/bin/env bash
LOGDIR=/srv/http/chaotic-aur/makepkglogs/_daily
cd /tmp

#  Do our directory
BUILDDIR="firefox.$(date '+%Y%m%d%H%M%S')"
mkdir -p "$BUILDDIR"
cd "$BUILDDIR" || exit

# Download our beloved firefox
repoctl down firefox-wayland-hg waterfox-current-git

# Librewish likes this forks
git clone https://github.com/torvic9/plasmafox.git
git clone https://github.com/torvic9/kplasmafoxhelper.git

# YAY!
echo '[build-firefox] Building! '
~/chaotic-batchbuild kplasmafoxhelper -- plasmafox -- firefox-hg -- firefox-wayland-hg

# Move logs around
echo '[build-firefox] Submiting logs:'
rm _add.log || echo 'No add?'
mv ./*.log "$LOGDIR/"

# Cleaning hour
echo '[build-firefox] Nuking temp directories'
cd ..
rm -rf --one-file-system "$BUILDDIR"

echo '[build-firefox] Removing logs from compiled packages'
cd "$LOGDIR"
~/chaotic-clean-logs

