#!/usr/bin/env bash
~/chaotic-base-update

cd /tmp

BUILDDIR="hourly.$(date '+%Y%m%d%H%M%S')"
mkdir -p "$BUILDDIR" || exit
cd "$BUILDDIR" || exit

echo '[build-hourly] Downloading found updates'
repoctl down -u

echo '[build-houry] Remove ignored packages'
cat ~/ignore-hourly.txt | xargs rm -rf

echo '[build-hourly] Download CVS except ignored packages'
PCVS=$(repoctl list |\
       	grep '\-\(git\|svn\|bzr\|hg\|nightly\)$' |\
	sort | comm -13 ~/ignore-hourly.txt -)

for v in $PCVS; do
	repoctl down $v
done

ls | xargs echo '[build-hourly] Building: '
~/chaotic-batchbuild

echo '[build-hourly] Submiting logs:'
LOGDIR=/srv/http/chaotic-aur/makepkglogs
mkdir -p "$LOGDIR"
mv ./*.log "$LOGDIR/"

echo '[build-hourly] Nuking temp directories'
cd ..
rm -rf "$BUILDDIR"

echo '[build-hourly] Removing logs from compiled packages'
cd "$LOGDIR"
TOREM=$(grep -l -P 'ERROR: (A|The) package( group)? has already been built' *.log)
[[ ! -z "$TOREM" ]] && echo "$TOREM" | xargs rm
TOREM=$(grep -l 'Created signature file' *.log)
[[ ! -z "$TOREM" ]] && echo "$TOREM" | xargs rm

echo '[build-hourly] Updating database and analytics'
~/chaotic-add
~/chaotic-status > /srv/http/chaotic-aur/analytics.html

~/chaotic-clean3
