#!/usr/bin/env bash
LOGDIR='/srv/http/chaotic-aur/makepkglogs/_daily'
cd /tmp

BUILDDIR="morning.$(date '+%Y%m%d%H%M%S')"
mkdir -p "$BUILDDIR" || exit
cd "$BUILDDIR" || exit

repoctl down vlc-git rpcs3-git wireguard-dkms-git mir-git ffmpeg-full retdec-git nss-hg firefox-wayland-hg firefox-hg
~/chaotic-batchbuild
rm add.log
mv ./*.log "$LOGDIR/"

cd ..
rm -rf "$BUILDDIR"

~/build-llvm
