#!/usr/bin/env bash
# Wine helpers
setup_wine() {
	git checkout customization.cfg PKGBUILD

	sed -i'' "
	s/_COMPILEWITH=\"[^\"]*\"/_COMPILEWITH=\"zapcc\"/g
	s/_OPTIMIZED=\"[^\"]*\"/_OPTIMIZED=\"false\"/g
	s/_NUKR=\"[^\"]*\"/_NUKR=\"false\"/g
	s/_NOINITIALPROMPT=\"[^\"]*\"/_NOINITIALPROMPT=\"true\"/g
	s/_use_staging=\"[^\"]*\"/_use_staging=\"$1\"/g
	s/_use_pba=\"[^\"]*\"/_use_pba=\"$2\"/g
	s/_use_gallium_nine=\"[^\"]*\"/_use_gallium_nine=\"$3\"/g
	" customization.cfg

	local _SRCINFO=$(makepkg -o --noprepare --printsrcinfo)
	export _PKGNAME=$(echo "$_SRCINFO" | grep -Po '(?<=pkgname = )(.*)$')
	export _PKGREL=$(echo "$_SRCINFO" | grep -Po '(?<=pkgrel = )(.*)$')
	#export _PKGVER=$(echo "$_SRCINFO" | grep -Po '(?<=pkgver = )(.*)$')

	echo "[!] Consulting version..."
	export _PKGVER=$(~/chaotic-pkgver | tail -n 1)
}

almostisolated_makepkg() {
	export TARGET_UPPER='wine'
	export TARGET_NUKE=0
	export TARGET_EXTRAPKGS='zapcc'
        ~/chaotic-makepkg \
		--noconfirm --sign \
                $@
	~/chaotic-add
}

# Clone TKG
cd /tmp
rm -rf TkG
git clone https://github.com/Tk-Glitch/PKGBUILDS.git TkG

# Build Wine
cd TkG/wine-tkg-git
for VARIATION in 'false false false' 'false false true' 'false true false' 'true true false' 'true false true' 'true false false'
do
        setup_wine $VARIATION
	
       	#_LASTVER_DIR="${HOME}/last-wine/${_PKGREL}"
        #_LASTVER_FILE="${_LASTVER_DIR}/${_PKGNAME}"
        #mkdir -p "$_LASTVER_DIR"
	
        #echo "[!] Package: ${_PKGNAME}-${_PKGVER}-${_PKGREL}"
        #if [[ ! -f "$_LASTVER_FILE" || "$(cat $_LASTVER_FILE)" != "$_PKGVER" ]]
        #then
        	echo "[!] Building"
		
	        almostisolated_makepkg -sc || continue
		
	        sed -i'' 's/_INSTALL_TO_OPT="false"/_INSTALL_TO_OPT="true"/g' customization.cfg
		
	        ln -srf "src/${_PKGNAME}-32-build" "src/${_PKGNAME/%-git/-opt-git}-32-build"
	        ln -srf "src/${_PKGNAME}-64-build" "src/${_PKGNAME/%-git/-opt-git}-64-build"
		
	        almostisolated_makepkg -R
		
		#echo "$_PKGVER" > "$_LASTVER_FILE"
	#fi
done

cd ..
sudo rm -rf wine-tkg-git

# Build Linux
#cd linux419-tkg
#echo "TkGExt=\"-tkg-muqss\"" > cpuschedset
#~/chaotic-makepkg --sign --noconfirm -c -C
#echo "TkGExt=\"-tkg-cfs\"" > cpuschedset
#~/chaotic-makepkg --sign --noconfirm -c -C
#echo "TkGExt=\"-tkg-pds\"" > cpuschedset
#~/chaotic-makepkg --sign --noconfirm -c -C

# Clean anything else
cd /tmp
sudo rm -rf TkG
