#!/usr/bin/env bash
LOGDIR='/srv/http/chaotic-aur/makepkglogs/_daily'
export TARGET_EXTRAPKGS='multilib-devel zapcc'
cd /tmp

echo '[!] Building'
repoctl down llvm-svn
cd llvm-svn
~/chaotic-makepkg --sign -sc --noconfirm 2>&1 | tee "$LOGDIR/llvm-svn"
echo '[!] Nuking'
cd ..
sudo rm -rf /tmp/llvm-svn

~/chaotic-add

echo '[!] 32 Building'
repoctl down lib32-llvm-svn
cd lib32-llvm-svn
~/chaotic-makepkg --sign -sc --noconfirm 2>&1 | tee "$LOGDIR/lib32-llvm-svn"
echo '[!] 32 Nuking'
cd ..
sudo rm -rf /tmp/lib32-llvm-svn

~/chaotic-add
