#!/usr/bin/env bash
LOGDIR='/srv/http/chaotic-aur/makepkglogs/_daily'
LCARLIERSRC='https://pkgbuild.com/~lcarlier/mesa-git/sources'
cd /tmp

echo '[!] 64 Building'
export TARGET_EXTRAPKGS=''
mkdir -p llvm
cd llvm
wget -q "$LCARLIERSRC/llvm-svn/"{PKGBUILD,llvm.patch,llvm-Config-llvm-config.h}
~/chaotic-makepkg --sign -c --noconfirm 2>&1 | tee "$LOGDIR/llvm-svn"
echo '[!] 64 Nuking'
cd ..
rm -rf /tmp/llvm

~/chaotic-add

echo '[!] 32 Building'
export TARGET_EXTRAPKGS='multilib-devel'
mkdir -p lib32-llvm
cd lib32-llvm
wget -q "$LCARLIERSRC/lib32-llvm-svn/"{PKGBUILD,llvm.patch}
~/chaotic-makepkg --sign -c --noconfirm 2>&1 | tee "$LOGDIR/lib32-llvm-svn"
echo '[!] 32 Nuking'
cd ..
rm -rf /tmp/lib32-llvm

~/chaotic-add
