#!/usr/bin/env bash
set -o errexit
cd /srv/http/chaotic-aur/x86_64

DUPLICATED=$(
  ls |\
    grep -Po "^(.*)(?=(?:(?:-[^-]*){3}\.pkg\.tar(?>\.xz)?)$)" |\
    uniq -d
)

if [[ -z "$DUPLICATED" ]]; then
	echo "No duplicate packages were found!"
else
	TO_MV=$(
	  echo "$DUPLICATED[@]" |\
	    awk '{print "find -name \""$1"*\" | grep -P \"\\.\\/"$1"(((-[^-]*){3}\\.pkg\\.tar(?>\\.xz)?))$\" | sort | head -n -1;"}' |\
	    bash |\
	    awk '{print $1"\n"$1".sig"}'
	)
	echo "[!] Moving:"
	echo "${TO_MV[*]}"
	echo "[!] Total: $(echo -n "${TO_MV[*]}" | wc -l)"
	read -r -p "[?] Are you sure? [y/N] " U_SURE
	case "$U_SURE" in
		[yY])
			mv -v -t ../archive/ ${TO_MV[*]}
esac
fi
