#!/usr/bin/env bash
function update_checkpoint() {
	if [ $(date -d "$_RUN_TIME" +'%s') -ge $(date -r ~/last-add +'%s') ]; then
		touch -d "$_RUN_TIME" ~/last-add
	fi
}

cd /srv/http/chaotic-aur/x86_64
if [[ ! -f "$HOME/last-add" ]]
then
	touch -d "$(date -R -r ./chaotic-aur.db.tar.gz)" ~/last-add
fi
export _RUN_TIME="$(date -R)"
export _NEW_SIGS="$(find *.sig -newer ~/last-add)"
if [[ "$_NEW_SIGS" != "" ]]
then
	export _PKGS=$(echo "$_NEW_SIGS" |\
		grep -Po '(.*)(?=(?:-(?:[^-]*)){3}\.pkg\.tar(?:\.xz)?\.sig)')
	echo "$_PKGS" |\
		xargs repoctl update \
		\
		&& update_checkpoint
	
fi
cat chaotic-aur.db.tar.gz | tar -tvz | grep -e "^d" | awk '{print $6}' > ../pkgs.txt

~/chaotic-clean2 --quiet
