#!/usr/bin/env sh
limit_build() {
	while [ `jobs | wc -l` -ge 4 ]; do
		sleep 3
	done
}

one_build() {
	cd "$1";
	~/chaotic-makepkg -cfs --sign --noconfirm  &> ../$1.log && cd ..  && rm -rf "$1" || cd ..
	echo "[@] Leaving: $1"
	~/chaotic-add &> add.log
}

for dir in ${@:-*}; do
	if [[ -d "$dir" ]]; then
		limit_build
		echo "[!] Building: $dir"
		one_build "$dir" &
	fi
done

echo '[!] Waiting all jobs to finish...'
wait
