#!/usr/bin/env sh

# * Defaults
CHROOT='/tmp/chaotic-chroot'
BASE='base-root'

# * CHROOT Lowdir
BASE_RUN="sudo systemd-nspawn -M update-base -u root -D $CHROOT/$BASE"
if [[ -d "$CHROOT/$BASE" ]]; then
	while [[ -f "$CHROOT/$BASE.lock" ]] || [[ -f "$CHROOT/$BASE/var/lib/pacman/db.lck" ]]; do
		sleep 1
	done
	echo $$ > "$CHROOT/$BASE.lock"
	echo '[chaotic-chroot] Updating lowerdir...'
	sudo mount --bind /tmp/chaotic-chroot/pacman-cache "$CHROOT/$BASE/var/cache/pacman/pkg"
	$BASE_RUN pacman -Syu --noconfirm
	$BASE_RUN pacman -Scc --noconfirm
	sudo umount "$CHROOT/$BASE/var/cache/pacman/pkg"
	rm "$CHROOT/$BASE.lock"
fi
