#!/usr/bin/env bash
cd /srv/http/chaotic-aur/x86_64 || exit
mkdir -p ../archive

TO_MV=$(
for pkg in *.sig
do
	if [ ! -f "${pkg%.sig}" ]; then echo "$pkg"; fi
done
)

if [[ ! -z "${TO_MV[*]}" ]]
then
	if [[ "$1" != "--quiet" ]]
	then
		echo "[!] Moving:"
		echo "${TO_MV[*]}"
		echo "[!] Total: $(echo -n "${TO_MV[*]}" | wc -l)"

		read -r -p "[?] Are you sure? [y/N] " U_SURE
		case "$U_SURE" in
			[yY])
				mv -v -t ../archive ${TO_MV[*]}
		esac
	else
		mv -t ../archive ${TO_MV[*]}
	fi
fi
