#!/usr/bin/env sh

# * Defaults
CHROOT='/tmp/chaotic-chroot'
BASE='base-root'
BUILD_USER='main-builder'

# * CHROOT Lowdir
BASE_RUN="sudo systemd-nspawn -M update-base -u root -D $CHROOT/$BASE"
if [[ -d "$CHROOT/$BASE" ]]; then
	while [[ -f "$CHROOT/$BASE.lock" ]] || [[ -f "$CHROOT/$BASE/var/lib/pacman/db.lck" ]]; do
		sleep 1
	done
	echo $$ > "$CHROOT/$BASE.lock"
	echo '[chaotic-chroot] Updating lowerdir...'
	sudo mount --bind /tmp/chaotic-chroot/pacman-cache "$CHROOT/$BASE/var/cache/pacman/pkg"
	$BASE_RUN pacman -Syu --noconfirm
	sudo umount "$CHROOT/$BASE/var/cache/pacman/pkg"
	cp -ar "/home/$BUILD_USER/.gnupg"/{pubring.kbx,tofu.db,trustdb.gpg,crls.d} "$CHROOT/$BASE/home/$BUILD_USER/.gnupg"
	cp -a "/home/$BUILD_USER/.gitconfig" "$CHROOT/$BASE/home/$BUILD_USER/"
	rm "$CHROOT/$BASE.lock"
fi
