#!/usr/bin/env bash

cd /srv/http/chaotic-aur/x86_64
if [[ ! -f "$HOME/last-add" ]]
then
	touch -d "$(date -R -r ./chaotic-aur.db.tar.gz)" ~/last-add
fi
_NEW_SIGS="$(find *.sig -newer ~/last-add)"
if [[ "$_NEW_SIGS" != "" ]]
then
	echo "" > ~/last-add
	echo "$_NEW_SIGS" |\
		grep -Po '(.*)(?=(?:-(?:[^-]*)){3}\.pkg\.tar(?:\.xz)?\.sig)' |\
		xargs 'repoctl update'
fi
cat chaotic-aur.db.tar.gz | tar -tvz | grep -e "^d" | awk '{print $6}' > ../pkgs.txt
